# Terragon Autonomous SDLC Configuration
# Repository: dp-flash-attention (ADVANCED maturity level)
# Generated: 2025-08-01

repository:
  name: "dp-flash-attention"
  maturity_level: "advanced"  # 75-85% SDLC maturity
  primary_language: "python"
  architecture: "cuda_ml_library"
  domain: "privacy_preserving_ml"

scoring:
  weights:
    advanced:
      wsjf: 0.5           # Business value and urgency
      ice: 0.1            # Impact-Confidence-Ease
      technicalDebt: 0.3  # High focus on debt reduction
      security: 0.1       # Security boost factor
    
  thresholds:
    minScore: 15          # Higher bar for advanced repos
    maxRisk: 0.7          # More conservative risk tolerance
    securityBoost: 2.0    # Security vulnerability multiplier
    complianceBoost: 1.8  # Compliance issue multiplier

discovery:
  sources:
    - gitHistory          # Analyze commits for TODO/FIXME patterns
    - staticAnalysis      # Code quality and complexity metrics
    - issueTrackers      # GitHub issues and PR feedback
    - vulnerabilityDatabases  # CVE and security advisories
    - performanceMonitoring   # GPU performance regressions
    - dependencyAudits   # Outdated packages and security patches
    
  analysis_tools:
    static:
      - "ruff"            # Python linting and code quality
      - "mypy"            # Type checking
      - "bandit"          # Security analysis
      - "semgrep"         # Advanced static analysis
    security:
      - "safety"          # Python dependency security
      - "pip-audit"       # Vulnerability scanning
      - "trivy"           # Container security
      - "codeql"          # GitHub security analysis
    performance:
      - "py-spy"          # Python profiling
      - "nvidia-smi"      # GPU monitoring
      - "pytest-benchmark" # Performance testing
    
  patterns:
    technical_debt:
      - "TODO|FIXME|HACK|XXX"     # Code comments
      - "temporary|quick.?fix"     # Commit messages
      - "complexity > 10"          # Cyclomatic complexity
      - "coverage < 80%"           # Test coverage gaps
    security_risks:
      - "CVE-\\d{4}-\\d{4,7}"     # CVE references
      - "SECURITY|security"        # Security-related issues
      - "vulnerability|exploit"    # Vulnerability mentions
    performance_issues:
      - "slow|performance|bottleneck"  # Performance concerns
      - "memory.?leak|oom"            # Memory issues
      - "gpu.?utilization < 50%"      # GPU efficiency

execution:
  constraints:
    maxConcurrentTasks: 1
    maxExecutionTimeHours: 4
    requiresReview: true
    
  validation:
    testRequirements:
      minCoverage: 85
      performanceRegression: 5  # Max 5% regression
      securityChecks: true
      privacyValidation: true   # DP-specific validation
      
  rollback:
    triggers:
      - testFailure
      - buildFailure
      - securityViolation
      - privacyViolation
      - performanceRegression
    autoRollback: true
    backupBranch: "auto-backup"

priorities:
  categories:
    - name: "security-critical"
      weight: 3.0
      autoExecute: true
    - name: "privacy-violation"
      weight: 2.5
      autoExecute: true
    - name: "performance-regression"
      weight: 2.0
      autoExecute: false
    - name: "technical-debt"
      weight: 1.5
      autoExecute: false
    - name: "dependency-update"
      weight: 1.2
      autoExecute: false
    - name: "documentation"
      weight: 0.8
      autoExecute: false

reporting:
  metrics:
    track:
      - executionSuccess
      - valueDelivered
      - technicalDebtReduction
      - securityImprovements
      - performanceGains
      - privacyGuarantees
    
  dashboards:
    - name: "value-delivery"
      url: "http://localhost:3000/value"
    - name: "technical-health"
      url: "http://localhost:3000/health"
      
  notifications:
    slack:
      enabled: false
      webhook: ""
    email:
      enabled: false
      recipients: []

advanced_features:
  ai_integration:
    enabled: true
    models:
      - "claude-3-5-sonnet"    # Code analysis and generation
      - "gpt-4"                # Alternative analysis
    capabilities:
      - codeReview
      - architectureAnalysis
      - performanceOptimization
      - securityAudit
      
  research_integration:
    enabled: true
    features:
      - paperAnalysis         # Track latest research
      - benchmarkComparison   # Compare with state-of-art
      - innovationTracking    # Identify opportunities
      
  compliance:
    frameworks:
      - SOC2
      - GDPR
      - CCPA
      - NIST
    automation:
      - auditTrail
      - policyValidation
      - complianceReporting