apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dp-flash-attention-hpa-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-flash-attention-production
  minReplicas: 5
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80