global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "dp_flash_attention_rules.yml"

scrape_configs:
  - job_name: 'dp-flash-attention'
    static_configs:
      - targets: ['dp-flash-attention:8081']
    scrape_interval: 10s
    metrics_path: /metrics
    
  - job_name: 'privacy-metrics'
    static_configs:
      - targets: ['dp-flash-attention:8081']
    scrape_interval: 30s
    metrics_path: /privacy-metrics
